services:
  frontend:
    build:
      context: .
    container_name: final-project-app
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
